CI test mode for debugging

diff --git a/.github/workflows/deploy-testbed.yaml b/.github/workflows/deploy-testbed.yaml
--- a/.github/workflows/deploy-testbed.yaml
+++ b/.github/workflows/deploy-testbed.yaml
@@ -19,13 +19,13 @@ jobs:
         toolchain: stable
         profile: minimal
 
-    - name: Running cache
-      uses: Swatinem/rust-cache@v1
-      with:
-        cache-on-failure: true
+#     - name: Running cache
+#       uses: Swatinem/rust-cache@v1
+#       with:
+#         cache-on-failure: true
     
-    - name: Running build
-      run: cargo build --all --release
+#     - name: Running build
+#       run: cargo build --all --release
 
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
@@ -33,26 +33,31 @@ jobs:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
 
-    - name: Upload with rsync
+    - name: Test upload with rsync
       run: |
-        rsync -avz \
-          ./target/release/samizdat-hub \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-hub &&
-        rsync -avz \
-          ./hub/samizdat-hub.service \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-hub.service
-        rsync -avz \
-          ./target/release/samizdat-node \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-node &&
-        rsync -avz \
-          ./node/samizdat-node.service \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-node.service
-        rsync -avz \
-          ./target/release/samizdat-proxy \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-proxy &&
-        rsync -avz \
-          ./proxy/samizdat-proxy.service \
-          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-proxy.service
+          echo 'test payload' > test.txt
+          rsync -avz ./test.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:test.txt
+      
+#     - name: Upload with rsync
+#       run: |
+#         rsync -avz \
+#           ./target/release/samizdat-hub \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-hub &&
+#         rsync -avz \
+#           ./hub/samizdat-hub.service \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-hub.service &&
+#         rsync -avz \
+#           ./target/release/samizdat-node \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-node &&
+#         rsync -avz \
+#           ./node/samizdat-node.service \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-node.service &&
+#         rsync -avz \
+#           ./target/release/samizdat-proxy \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/local/bin/samizdat-proxy &&
+#         rsync -avz \
+#           ./proxy/samizdat-proxy.service \
+#           ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/etc/systemd/system/samizdat-proxy.service
     
     - name: Restart hub
       run: |
@@ -63,7 +68,7 @@ jobs:
            rm -rf /var/samizdat/node/db &&
            systemctl enable --now samizdat-hub &&
            systemctl enable --now samizdat-node &&
-           systemctl enable --now samizdat-proxy"
+           systemctl enable --now samizdat-proxy || echo skipping"
     
     - name: Done
       run: echo Done
